package net.soleheart.creditcardhelper.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CREDIT_CARD.
 */
public class CreditCard implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String bankName;
    private int billDate;
    private int payDate;
    /** Not-null value. */
    private String lastDigits;

    public CreditCard() {
    }

    public CreditCard(Long id) {
        this.id = id;
    }

    public CreditCard(Long id, String bankName, int billDate, int payDate, String lastDigits) {
        this.id = id;
        this.bankName = bankName;
        this.billDate = billDate;
        this.payDate = payDate;
        this.lastDigits = lastDigits;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBankName() {
        return bankName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public int getBillDate() {
        return billDate;
    }

    public void setBillDate(int billDate) {
        this.billDate = billDate;
    }

    public int getPayDate() {
        return payDate;
    }

    public void setPayDate(int payDate) {
        this.payDate = payDate;
    }

    /** Not-null value. */
    public String getLastDigits() {
        return lastDigits;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLastDigits(String lastDigits) {
        this.lastDigits = lastDigits;
    }

}
